package com.gosoft.gobtp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OuvrierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOuvrierAllPropertiesEquals(Ouvrier expected, Ouvrier actual) {
        assertOuvrierAutoGeneratedPropertiesEquals(expected, actual);
        assertOuvrierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOuvrierAllUpdatablePropertiesEquals(Ouvrier expected, Ouvrier actual) {
        assertOuvrierUpdatableFieldsEquals(expected, actual);
        assertOuvrierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertOuvrierMapsIdRelationshipPersistedValue(Ouvrier entityToPersist, Ouvrier persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getInternalUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOuvrierAutoGeneratedPropertiesEquals(Ouvrier expected, Ouvrier actual) {
        assertThat(expected)
            .as("Verify Ouvrier auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOuvrierUpdatableFieldsEquals(Ouvrier expected, Ouvrier actual) {
        assertThat(expected)
            .as("Verify Ouvrier relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOuvrierUpdatableRelationshipsEquals(Ouvrier expected, Ouvrier actual) {
        // empty method
    }
}
